# Generated by Django 3.0.2 on 2020-01-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subBluedit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
